// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD23PpIaGy553iI8zvWkGsniCkxjjmy8lg',
    appId: '1:798212628790:web:23ee921225816ce4931397',
    messagingSenderId: '798212628790',
    projectId: 'redditclone-f3a68',
    authDomain: 'redditclone-f3a68.firebaseapp.com',
    storageBucket: 'redditclone-f3a68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwk-avNNBsCBez2phNkP7nHiMEXI_PGc',
    appId: '1:798212628790:android:f88784c57b6ba9d1931397',
    messagingSenderId: '798212628790',
    projectId: 'redditclone-f3a68',
    storageBucket: 'redditclone-f3a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PjGvizveKfHwVBT_YJTMjVD3D7oOn7w',
    appId: '1:798212628790:ios:f5847a907ca4cea0931397',
    messagingSenderId: '798212628790',
    projectId: 'redditclone-f3a68',
    storageBucket: 'redditclone-f3a68.appspot.com',
    iosClientId: '798212628790-il7t40v0tch34oq4dar4rgf0klh7h0qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.reditClone',
  );
}
